color: null
fieldLayouts:
  e33f8044-cf16-4605-bc3d-09679348a498:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-30T22:58:38+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 205c8050-85f3-478e-b411-c7e6073f9b3e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-30T23:04:32+00:00'
            elementCondition: null
            fieldUid: cd489d3c-f914-475c-a270-ab926e4e7485 # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fc08c7a-1dfa-40d0-b234-5540eae14b50
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b1d8412f-75ff-4e81-896b-ef3b9e203f18
        userCondition: null
handle: richText
hasTitleField: false
icon: font-case
name: 'Rich Text'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
