headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Advanced
toolbar:
  - undo
  - redo
  - heading
  - style
  - '|'
  - bold
  - italic
  - underline
  - link
  - blockQuote
  - '|'
  - bulletedList
  - numberedList
  - outdent
  - indent
  - '|'
  - removeFormat
