defaultPlacement: end
fieldLayouts:
  97e108bc-3ae9-4cb4-b411-5d7ff009317f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-07T20:31:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 8f82b7c2-236e-425b-aee6-ed3cddaac801
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-07T20:31:45+00:00'
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 18a38e5b-1cd8-43af-9201-30965f368265
            userCondition: null
            warning: null
          -
            attribute: newWindow
            dateAdded: '2024-10-07T20:31:45+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: 7af94ebf-691c-4b28-a1ae-a45b423b3ff6
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: 5a55d1b4-345e-4723-9560-70ffd6fd3cc9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2024-10-07T20:31:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: 8f1bb23d-c6f6-46fd-9531-0787c7af3117
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            dateAdded: '2024-10-07T20:31:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: 3f040942-0984-415b-8cdf-6b96d415feec
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            dateAdded: '2024-10-07T20:31:45+00:00'
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: bb42c798-5ce0-4769-a539-e3bbc1f2b6da
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: 8c5d3a75-0d4e-4d39-9512-1d4f09814ecf
        userCondition: null
handle: footerNavigation
instructions: ''
maxNodes: null
name: 'Footer Navigation'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagationMethod: all
siteSettings:
  35b563a0-4662-40b9-b885-a8450a2868d9: # Viget Craft Starter
    enabled: true
sortOrder: 2
structure:
  maxLevels: 2
  uid: 622b09f1-9e19-4176-a61a-69d6f7cda562
