baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Viget Craft Starter'
primary: true
siteGroup: 805d8826-faed-4186-9b88-f509eb9b07e6 # Viget Craft Starter
sortOrder: 1
