columnSuffix: null
handle: newWindow
instructions: null
name: 'Open Link In New Window'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
