columnSuffix: null
handle: pageBlocks
instructions: null
name: 'Page Blocks'
searchable: false
settings:
  createButtonLabel: 'New Block'
  entryTypes:
    - 896b8f2a-ed0c-42c9-b5fd-ba8668fc6784 # Rich Text
    - 7ced3e9d-9b54-47f6-8103-e5c3a4fbaf9c # Card Grid
    - 3bcf7ddb-71e7-4115-868c-815b3611b34c # Text With Media
    - 534ccdd8-7abd-4300-a102-71885b21c126 # Call To Action
    - 27f19bae-64f8-47b8-9fc9-7552e11e2656 # Page Hero
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
