columnSuffix: null
handle: richTextSimple
instructions: null
name: 'Rich Text: Simple'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: b7e66782-af96-4012-9e17-914134073ced # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
