columnSuffix: null
handle: richText
instructions: null
name: 'Rich Text'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  css: "/* Hides style buttons that don't apply to selection */\r\n.ck-style-grid__button.ck-disabled { display: none!important; }\r\n\r\n.ck.ck-content .rich-text-size-xlarge {\r\n  font-size: 32px;\r\n  line-height: 1.2;\r\n}\r\n\r\n.ck.ck-content .rich-text-size-large {\r\n  font-size: 24px;\r\n  line-height: 1.2;\r\n}\r\n\r\n.ck.ck-content .rich-text-size-medium {\r\n  font-size: 18px;\r\n  line-height: 1.2;\r\n}\r\n\r\n.ck.ck-content .rich-text-size-small {\r\n  font-size: 12px;\r\n  line-height: 1.2;\r\n}"
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  fullGraphqlData: false
  headingLevels: false
  js: "/**\r\n * Takes a given definition and creates that definition for the tags defined in elements\r\n */\r\nfunction defintionsForElements(definition, elements = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p']) {\r\n  return elements.map((element) => ({\r\n    ...definition,\r\n    element,\r\n    name: `${definition.name} - ${element}`\r\n  }))\r\n}\r\n\r\ndebugger\r\n\r\nreturn {\r\n  list: {\r\n    properties: {\r\n      styles: false,\r\n    },\r\n  },\r\n  fontSize: {\r\n            options: [\r\n                'a',\r\n                'b',\r\n                'c',\r\n                'd',\r\n                'e',\r\n            ]\r\n        },\r\n  style: {\r\n    definitions: [\r\n      ...defintionsForElements({\r\n        name: 'Heading XXL',\r\n        classes: [\r\n          'richtext-heading-xxl',\r\n        ],\r\n      }),\r\n      ...defintionsForElements({\r\n        name: 'Heading XL',\r\n        classes: [\r\n          'richtext-heading-xl',\r\n        ],\r\n      }),\r\n      ...defintionsForElements({\r\n        name: 'Heading XL',\r\n        classes: [\r\n          'richtext-heading-xl',\r\n        ],\r\n      })\r\n    ],\r\n  },\r\n}"
  options: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  toolbar:
    - undo
    - redo
    - style
    - fontSize
    - '|'
    - bold
    - italic
    - underline
    - link
    - blockQuote
    - '|'
    - bulletedList
    - numberedList
    - outdent
    - indent
    - '|'
    - removeFormat
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
