dateModified: 1727796858
email:
  fromEmail: $SYSTEM_EMAIL_FROM
  fromName: 'Viget Craft Starter'
  replyToEmail: null
  template: null
  transportSettings:
    host: $SYSTEM_EMAIL_HOSTNAME
    password: $SYSTEM_EMAIL_PASSWORD
    port: $SYSTEM_EMAIL_PORT
    useAuthentication: '1'
    username: $SYSTEM_EMAIL_USERNAME
  transportType: craft\mail\transportadapters\Smtp
fs:
  local:
    hasUrls: true
    name: Local
    settings:
      path: '@webroot/assets'
    type: craft\fs\Local
    url: /assets/
meta:
  __names__:
    0e7762a5-2553-4c0d-b8af-9b43b59524bf: Home # Home
    3bcf7ddb-71e7-4115-868c-815b3611b34c: 'Text With Media' # Text With Media
    3f1dc0c5-f091-469a-858a-4cbd3596bab7: 'Icon Card' # Icon Card
    5e84b0b7-6851-47ed-962e-76498ac9476f: 'Card Grid' # Card Grid
    7bd21dd3-6b12-4163-8432-030ea6a3f8d3: 'Page Blocks' # Page Blocks
    7ced3e9d-9b54-47f6-8103-e5c3a4fbaf9c: 'Card Grid' # Card Grid
    7d418368-91eb-4c64-8f5b-94c62cd62359: 'Image Card' # Image Card
    0011a64a-91b6-4aa3-98e6-be048394a2cf: Icon # Icon
    27f19bae-64f8-47b8-9fc9-7552e11e2656: 'Page Hero' # Page Hero
    35b563a0-4662-40b9-b885-a8450a2868d9: 'Viget Craft Starter' # Viget Craft Starter
    55cc26b6-8b49-47de-bbe7-5908da6f4545: 'Video Url' # Video Url
    69fe4c18-21c9-4a3d-8fce-9988d3f741e4: Link # Link
    534ccdd8-7abd-4300-a102-71885b21c126: 'Call To Action' # Call To Action
    570fb481-ad97-46db-8bad-f7b0fd90e831: Image # Image
    805d8826-faed-4186-9b88-f509eb9b07e6: 'Viget Craft Starter' # Viget Craft Starter
    896b8f2a-ed0c-42c9-b5fd-ba8668fc6784: 'Rich Text' # Rich Text
    969acdd6-6362-41b1-b782-6bbd43a8a6b4: Home # Home
    167784f4-27c4-45bc-bcf4-eee051e54bd6: 'Open Link In New Window' # Open Link In New Window
    853413e4-e02c-487e-81a5-04e58eb18683: Assets # Assets
    a99edea2-f8ae-44e5-a12f-89cb9aa66738: Description # Description
    ac3b0590-d417-429e-aa1f-96be3c79a5b0: 'Media Type' # Media Type
    b7e66782-af96-4012-9e17-914134073ced: Simple # Simple
    b80d8ac7-5039-4535-afa5-82ec086e2f61: 'Link Text' # Link Text
    c52a9170-652b-4d92-a226-69894b1822ed: 'Rich Text: Simple' # Rich Text: Simple
    cd489d3c-f914-475c-a270-ab926e4e7485: 'Rich Text' # Rich Text
    d7f9c488-b14d-48c2-b6fc-d616b7a9f49f: 'Show Media On' # Show Media On
    d39724b0-dd22-4c74-aa0b-87a022555cf2: Advanced # Advanced
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  classnames:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  empty-coalesce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  imager-x:
    edition: lite
    enabled: true
    licenseKey: REPLACE
    schemaVersion: 4.0.0
  imager-x-power-pack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: REPLACE
    schemaVersion: 2.1.0
  retour:
    edition: standard
    enabled: true
    licenseKey: REPLACE
    schemaVersion: 3.0.12
  seomatic:
    edition: standard
    enabled: true
    licenseKey: REPLACE
    schemaVersion: 3.0.12
  viget-parts-kit:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Viget Craft Starter'
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
