defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 25362218-e66c-494e-9f2c-63e8cbc6ce0a # Global Code
handle: globalCode
maxAuthors: 1
minAuthors: 1
name: 'Global Code'
propagationMethod: all
siteSettings:
  35b563a0-4662-40b9-b885-a8450a2868d9: # Viget Craft Starter
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
